---
title: "PHP 2550 HW 6"
author: "Blain Morin"
date: "December 2, 2018"
output: pdf_document
header-includes:
- \usepackage{float}
---


```{r, echo = FALSE, message = FALSE, warning = FALSE}

set.seed(100)

### Load Libraries

library(knitr)
library(readr)
library(ggplot2)
library(dplyr)
library(stargazer)
library(splines)
library(gam)
library(extrafont)
library(grid)
library(gridExtra)
library(caret)

```

```{r, echo = FALSE, message = FALSE, warning = FALSE}

### Load and Clean Data procedure from hw5

### Load data
iod = read_csv("iodatadev.csv")

### Filter out columns with more that 10% missing data
iod.clean = Filter(function(x) mean(is.na(x)) < 0.1, iod)

### Get complete cases
iod.clean = iod.clean %>%
  filter(complete.cases(.))

### Remove ids, collinear terms, and unknown variables 
iod.clean = iod.clean %>%
  select(-X1, -ID, -"..2", -"..2_1", -CSG, -drds, - rass1)

### Select the variables from homework 5
iod.clean = iod.clean %>%
  select(GFR, SUN, SCR, AGE, FEMALE, cys, Diabetes, BMI, BLACK)
  

```

```{r, echo = FALSE, fig.height=5, fig.width=8, fig.align='center'}

### First consider log transforms of continuous variables

### Use log GFR?

gfr.qq = iod.clean %>%
  ggplot(aes(sample = scale(GFR))) +
  stat_qq() + stat_qq_line() +
  stat_qq(aes(sample = scale(log(GFR))), color = "blue") +
  ylab("Sample Quantile") + 
  xlab("Theoretical Quantile") +
  ggtitle("qqPlot: GFR (Black) vs log GFR (Blue)") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"))
  

gfr.qq


```

```{r, echo = FALSE}

###Add log(GFR)

iod.clean = iod.clean %>%
  mutate(logGFR = log(GFR))

###Add log of all cont. variables

iod.clean = iod.clean %>%
  mutate(logSUN = log(SUN),
         logSCR = log(SCR),
         logAGE = log(AGE),
         logcys = log(cys),
         logBMI = log(BMI))

```


```{r, echo = FALSE, fig.width=12, fig.height=12}

sun.smooth = iod.clean %>%
  ggplot(aes(y = logGFR, x = SUN)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5) +
  ylab("log(GFR)") +
  xlab("SUN") +
  ggtitle("log(GFR) vs SUN") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"))

scr.smooth = iod.clean %>%
  ggplot(aes(y = logGFR, x = SCR)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE) +
  ylab("log(GFR)") +
  xlab("SCR") +
  ggtitle("log(GFR) vs SCR") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"))

age.smooth = iod.clean %>%
  ggplot(aes(y = logGFR, x = AGE)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE) +
  ylab("log(GFR)") +
  xlab("AGE") +
  ggtitle("log(GFR) vs AGE") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"))

cys.smooth = iod.clean %>%
  ggplot(aes(y = logGFR, x = cys)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE) +
  ylab("log(GFR)") +
  xlab("CYS") +
  ggtitle("log(GFR) vs CYS") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"))

bmi.smooth = iod.clean %>%
  ggplot(aes(y = logGFR, x = BMI)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE) +
  ylab("log(GFR)") +
  xlab("BMI") +
  ggtitle("log(GFR) vs BMI") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans"))

grid.arrange(sun.smooth, scr.smooth,
             age.smooth, cys.smooth,
             bmi.smooth,
             nrow = 3)
  


```


```{r, echo = FALSE}


### Function for best polynomial 


bestpoly = function(x, y, folds, maxpoly){
  
  leaveout = createFolds(x, k = folds)
  error.matrix = matrix(NA, nrow = folds, ncol = maxpoly)
  
  for (i in 1:folds) {
    
    trainx = x[-leaveout[[i]]]
    trainy = y[-leaveout[[i]]]
    
    testx = x[leaveout[[i]]]
    testy = y[leaveout[[i]]]
    
    train.mat = as.data.frame(cbind(y=trainy, x = trainx))
    test.mat = as.data.frame(cbind(y = testy, x = testx))
    
    for (j in 1:maxpoly) {
      
      mod = lm(y ~ poly(x, degree = j, raw = TRUE), data = train.mat)
      preds = predict(mod, newdata = test.mat)
      error = mean((testy - preds)^2)
      error.matrix[i,j] = error
      
    }
    
  }
  
  ave.mse = apply(error.matrix, 2, mean)
  
  return(ave.mse)
  
  
}


```

```{r, echo = FALSE}

### Function for best step (equal breaks)


beststep = function(x, y, folds, maxbreaks){
  
  leaveout = createFolds(x, k = folds)
  error.matrix = matrix(NA, nrow = folds, ncol = maxbreaks-1)
  
  for (j in 2:maxbreaks) {
    
    a = cut(as.numeric(x), breaks = j)
    
    for (i in 1:folds) {
      
      trainx = a[-leaveout[[i]]]
      trainy = y[-leaveout[[i]]]
    
      testx = a[leaveout[[i]]]
      testy = y[leaveout[[i]]]
    
      train.mat = as.data.frame(cbind(y=trainy, b = trainx))
      test.mat = as.data.frame(cbind(y = testy, b = testx))
      
      
      
      mod = lm(y ~ as.factor(b), data = train.mat)
      preds = predict(mod, newdata = test.mat)
      error = mean((testy - preds)^2)
      error.matrix[i, j-1] = error
      
    }
    
  }
  
  ave.mse = apply(error.matrix, 2, mean)
  names(ave.mse) = 2:maxbreaks
  
  return(ave.mse)
  
  
}




```

```{r, echo = FALSE}

bestspline = function(x, y, folds, dfs) {
  leaveout = createFolds(x, k = folds)
  error.matrix = matrix(NA, nrow = folds, ncol = dfs)
  
  for (i in 1:folds) {
    
    trainx = x[-leaveout[[i]]]
    trainy = y[-leaveout[[i]]]
    
    testx = x[leaveout[[i]]]
    testy = y[leaveout[[i]]]
    
    train.mat = as.data.frame(cbind(y=trainy, x = trainx))
    test.mat = as.data.frame(cbind(y = testy, x = testx))

    for (j in 1:dfs) {
      
      fit.nspline=lm(y~ns(x,df=j),data=train.mat)  #Fit natural spline
      preds=predict(fit.nspline,newdata=test.mat,se=T)$fit
      
      error = mean((testy - preds)^2)
      error.matrix[i,j] = error
    }
  }
  
  ave.mse = apply(error.matrix, 2, mean)
  
  return(ave.mse)
}

```

```{r, echo = FALSE}

### Colors for legend

cols <- c("Smoothing Spline"="#f04546","Best Step"="#3591d1","Best Poly"="#62c76b", "Best Natural Spline" = "yellow")

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### SUN best transforms


### Poly
sun.best.poly = which.min(bestpoly(x = iod.clean$SUN, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

sun.poly.mod = lm(logGFR ~ poly(SUN, sun.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(sun.poly.preds = predict(sun.poly.mod))


### Step

sun.best.step = which.min(beststep(x = iod.clean$SUN, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

sun.step.mod = lm(logGFR ~ cut(SUN, breaks = sun.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(sun.step.preds = predict(sun.step.mod))


### Spline

sun.best.spline = which.min(bestspline(x = iod.clean$SUN, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

sun.spline.mod = lm(logGFR ~ ns(SUN, df = sun.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(sun.spline.preds = predict(sun.spline.mod))

sun.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = SUN)) +
  geom_point() +
  geom_smooth(aes(colour = "Smoothing Spline"), method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5) +
  ylab("log(GFR)") +
  xlab("SUN") +
  ggtitle("log(GFR) vs SUN") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = sun.step.preds, colour = "Best Step"), size = 1.5) +
  geom_line(aes(y = sun.poly.preds, colour = "Best Poly"), size = 1.5) +
  geom_line(aes(y = sun.spline.preds, colour = "Best Natural Spline"), size = 1.5) +
  scale_colour_manual(name = "Legend", values = cols)
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### SCR best transforms


### Poly
scr.best.poly = which.min(bestpoly(x = iod.clean$SCR, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

scr.poly.mod = lm(logGFR ~ poly(SCR, scr.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(scr.poly.preds = predict(scr.poly.mod))


### Step

scr.best.step = which.min(beststep(x = iod.clean$SCR, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

scr.step.mod = lm(logGFR ~ cut(SCR, breaks = scr.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(scr.step.preds = predict(scr.step.mod))


### Spline

scr.best.spline = which.min(bestspline(x = iod.clean$SCR, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

scr.spline.mod = lm(logGFR ~ ns(SCR, df = scr.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(scr.spline.preds = predict(scr.spline.mod))

scr.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = SCR)) +
  geom_point() +
  geom_smooth(aes(colour = "Smoothing Spline"), method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5) +
  ylab("log(GFR)") +
  xlab("SCR") +
  ggtitle("log(GFR) vs SCR") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = scr.step.preds, colour = "Best Step"), size = 1.5) +
  geom_line(aes(y = scr.poly.preds, colour = "Best Poly"), size = 1.5) +
  geom_line(aes(y = scr.spline.preds, colour = "Best Natural Spline"), size = 1.5) +
  scale_colour_manual(name = "Legend", values = cols)
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### AGE best transforms


### Poly
age.best.poly = which.min(bestpoly(x = iod.clean$AGE, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

age.poly.mod = lm(logGFR ~ poly(AGE, age.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(age.poly.preds = predict(age.poly.mod))


### Step

age.best.step = which.min(beststep(x = iod.clean$AGE, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

age.step.mod = lm(logGFR ~ cut(AGE, breaks = age.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(age.step.preds = predict(age.step.mod))


### Spline

age.best.spline = which.min(bestspline(x = iod.clean$AGE, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

age.spline.mod = lm(logGFR ~ ns(AGE, df = age.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(age.spline.preds = predict(age.spline.mod))

age.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = AGE)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("AGE") +
  ggtitle("log(GFR) vs AGE") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = age.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = age.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = age.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### cys best transforms


### Poly
cys.best.poly = which.min(bestpoly(x = iod.clean$cys, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

cys.poly.mod = lm(logGFR ~ poly(cys, cys.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(cys.poly.preds = predict(cys.poly.mod))


### Step

cys.best.step = which.min(beststep(x = iod.clean$cys, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

cys.step.mod = lm(logGFR ~ cut(cys, breaks = cys.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(cys.step.preds = predict(cys.step.mod))


### Spline

cys.best.spline = which.min(bestspline(x = iod.clean$cys, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

cys.spline.mod = lm(logGFR ~ ns(cys, df = cys.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(cys.spline.preds = predict(cys.spline.mod))

cys.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = cys)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("CYS") +
  ggtitle("log(GFR) vs CYS") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = cys.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = cys.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = cys.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=12, fig.width=9}

### BMI best transforms


### Poly
bmi.best.poly = which.min(bestpoly(x = iod.clean$BMI, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

bmi.poly.mod = lm(logGFR ~ poly(BMI, bmi.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(bmi.poly.preds = predict(bmi.poly.mod))


### Step

bmi.best.step = which.min(beststep(x = iod.clean$BMI, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 5))

bmi.step.mod = lm(logGFR ~ cut(BMI, breaks = bmi.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(bmi.step.preds = predict(bmi.step.mod))


### Spline

bmi.best.spline = which.min(bestspline(x = iod.clean$BMI, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

bmi.spline.mod = lm(logGFR ~ ns(BMI, df = scr.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(bmi.spline.preds = predict(bmi.spline.mod))

bmi.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = BMI)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("BMI") +
  ggtitle("log(GFR) vs BMI") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = bmi.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = bmi.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = bmi.spline.preds), colour = "yellow", size = 1.5) 
  

```



```{r, echo = FALSE, fig.height=10, fig.width=10}

### log SUN best transforms


### Poly
log.sun.best.poly = which.min(bestpoly(x = iod.clean$logSUN, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

log.sun.poly.mod = lm(logGFR ~ poly(logSUN, log.sun.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(log.sun.poly.preds = predict(log.sun.poly.mod))


### Step

log.sun.best.step = which.min(beststep(x = iod.clean$logSUN, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 5))

log.sun.step.mod = lm(logGFR ~ cut(logSUN, breaks = log.sun.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.sun.step.preds = predict(log.sun.step.mod))


### Spline

log.sun.best.spline = which.min(bestspline(x = iod.clean$logSUN, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

log.sun.spline.mod = lm(logGFR ~ ns(logSUN, df = log.sun.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.sun.spline.preds = predict(log.sun.spline.mod))

log.sun.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = logSUN)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("log(SUN)") +
  ggtitle("log(GFR) vs log(SUN)") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = log.sun.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = log.sun.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = log.sun.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### log SCR best transforms


### Poly
log.scr.best.poly = which.min(bestpoly(x = iod.clean$logSCR, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

log.scr.poly.mod = lm(logGFR ~ poly(logSCR, log.scr.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(log.scr.poly.preds = predict(log.scr.poly.mod))


### Step

log.scr.best.step = which.min(beststep(x = iod.clean$logSCR, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

log.scr.step.mod = lm(logGFR ~ cut(logSCR, breaks = log.scr.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.scr.step.preds = predict(log.scr.step.mod))


### Spline

log.scr.best.spline = which.min(bestspline(x = iod.clean$logSCR, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

log.scr.spline.mod = lm(logGFR ~ ns(logSCR, df = log.scr.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.scr.spline.preds = predict(log.scr.spline.mod))

log.scr.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = logSCR)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("log(SCR)") +
  ggtitle("log(GFR) vs log(SCR)") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = log.scr.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = log.scr.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = log.scr.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### log AGE best transforms


### Poly
log.age.best.poly = which.min(bestpoly(x = iod.clean$logAGE, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 6))

log.age.poly.mod = lm(logGFR ~ poly(logAGE, log.age.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(log.age.poly.preds = predict(log.age.poly.mod))


### Step

log.age.best.step = which.min(beststep(x = iod.clean$logAGE, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

log.age.step.mod = lm(logGFR ~ cut(logAGE, breaks = log.age.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.age.step.preds = predict(log.age.step.mod))


### Spline

log.age.best.spline = which.min(bestspline(x = iod.clean$logAGE, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

log.age.spline.mod = lm(logGFR ~ ns(logAGE, df = log.age.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.age.spline.preds = predict(log.age.spline.mod))

log.age.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = logAGE)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("log(AGE)") +
  ggtitle("log(GFR) vs log(AGE)") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = log.age.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = log.age.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = log.age.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### log cys best transforms


### Poly
log.cys.best.poly = which.min(bestpoly(x = iod.clean$logcys, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 10))

log.cys.poly.mod = lm(logGFR ~ poly(logcys, log.cys.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(log.cys.poly.preds = predict(log.cys.poly.mod))


### Step

log.cys.best.step = which.min(beststep(x = iod.clean$logcys, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 10))

log.cys.step.mod = lm(logGFR ~ cut(logcys, breaks = log.cys.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.cys.step.preds = predict(log.cys.step.mod))


### Spline

log.cys.best.spline = which.min(bestspline(x = iod.clean$logcys, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

log.cys.spline.mod = lm(logGFR ~ ns(logcys, df = log.cys.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.cys.spline.preds = predict(log.cys.spline.mod))

log.cys.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = logcys)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("log(CYS)") +
  ggtitle("log(GFR) vs log(CYS)") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = log.cys.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = log.cys.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = log.cys.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=10, fig.width=10}

### log BMI best transforms


### Poly
log.bmi.best.poly = which.min(bestpoly(x = iod.clean$logBMI, y = iod.clean$logGFR, 
                         folds = 10, maxpoly = 6))

log.bmi.poly.mod = lm(logGFR ~ poly(logBMI, log.bmi.best.poly), data = iod.clean)

iod.clean = iod.clean %>%
  mutate(log.bmi.poly.preds = predict(log.bmi.poly.mod))


### Step

log.bmi.best.step = which.min(beststep(x = iod.clean$logBMI, y = iod.clean$logGFR,
                                   folds = 10, maxbreaks = 5))

log.bmi.step.mod = lm(logGFR ~ cut(logBMI, breaks = log.bmi.best.step + 1), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.bmi.step.preds = predict(log.bmi.step.mod))


### Spline

log.bmi.best.spline = which.min(bestspline(x = iod.clean$logBMI, y = iod.clean$logGFR,
                                   folds = 10, dfs = 10))

log.bmi.spline.mod = lm(logGFR ~ ns(logBMI, df = log.scr.best.spline), data = iod.clean)


iod.clean = iod.clean %>%
  mutate(log.bmi.spline.preds = predict(log.bmi.spline.mod))

log.bmi.transforms = iod.clean %>%
  ggplot(aes(y = logGFR, x = logBMI)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "cs"), se = FALSE, size = 1.5, colour = "blue") +
  ylab("log(GFR)") +
  xlab("log(BMI)") +
  ggtitle("log(GFR) vs log(BMI)") +
  theme_classic() +
  theme(text=element_text(size=12,  family="CM Sans")) +
  geom_line(aes(y = log.bmi.step.preds), colour = "red", size = 1.5) +
  geom_line(aes(y = log.bmi.poly.preds), colour = "green", size = 1.5) +
  geom_line(aes(y = log.bmi.spline.preds), colour = "yellow", size = 1.5) 
  

```

```{r, echo = FALSE, fig.height=12, fig.width=10}

### test all plots

grid.arrange(sun.transforms, log.sun.transforms,
             scr.transforms, log.scr.transforms,
             age.transforms, log.age.transforms,
             cys.transforms, log.cys.transforms,
             bmi.transforms, log.bmi.transforms,
             ncol = 2)


```
